/*
 * Concatenate ./styles/*.css into the single stylesheet Obsidian loads.
 *
 * The shards are listed in cascade order, not alphabetically, so "which rule
 * wins" is decided here rather than by a filename.
 */

import fs from "fs";
import path from "path";

const STYLE_DIR = "styles";
const OUTFILE = "styles.css";

/** Concatenation order. Changing it changes which rule wins. */
export const SHARDS = [
  "tokens.css",
  "shell.css",
  "sidebar.css",
  "track-list.css",
  "track-rows.css",
  "player-bar.css",
  "sliders.css",
  "modal.css",
  "settings.css",
];

const BANNER = `/*
Generated by build-styles.mjs — do not edit.
Edit the shards in ./styles/ instead; this file is overwritten on every build.
*/

`;

export function readStyles() {
  const parts = SHARDS.map((name) => {
    const file = path.join(STYLE_DIR, name);
    if (!fs.existsSync(file)) throw new Error(`missing style shard: ${file}`);
    return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n").replace(/\s+$/, "");
  });
  return BANNER + parts.join("\n\n") + "\n";
}

export function buildStyles() {
  const css = readStyles();
  const previous = fs.existsSync(OUTFILE) ? fs.readFileSync(OUTFILE, "utf8") : null;
  if (previous === css) return false;
  fs.writeFileSync(OUTFILE, css);
  return true;
}

/** In dev mode, rebuild whenever a shard changes. */
export function watchStyles(onRebuild) {
  for (const name of SHARDS) {
    fs.watch(path.join(STYLE_DIR, name), () => {
      if (buildStyles()) onRebuild?.(name);
    });
  }
}
