import esbuild from "esbuild";
import process from "process";
import { buildStyles, watchStyles } from "./build-styles.mjs";

const banner = `/*
This file is generated by esbuild. Edit the TypeScript sources in ./src instead.
*/`;

const prod = process.argv[2] === "production";

const external = [
  "obsidian",
  "electron",
  "@electron/remote",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  "assert", "buffer", "child_process", "cluster", "crypto", "dgram", "dns",
  "domain", "events", "fs", "http", "https", "net", "os", "path", "punycode",
  "querystring", "readline", "stream", "string_decoder", "timers", "tls",
  "tty", "url", "util", "v8", "vm", "zlib",
  "node:fs", "node:path", "node:url", "node:crypto", "node:os",
];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

// Obsidian loads one stylesheet per plugin, so the shards in ./styles are
// concatenated into styles.css on every build — see build-styles.mjs.
buildStyles();

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  watchStyles((name) => console.log(`[styles] ${name} -> styles.css`));
  await context.watch();
}
